### ISSUE TITLE
Chain actions

### ISSUE THREAD

**Issue by zbraniecki** [bitovi/use-simple-reducer#18]
It should be possible to chain actions or react to action being rejected.

**Comment by shoumaw** [comment]
Hi @zbraniecki

Thanks for your comment but I just want to make sure I understand your suggestions clearly.
What do you exactly mean by chain actions? Since currently, queued actions are executed sequentially with each action being passed the latest modified state.

Also, there is an `error` field that is being returned if any of the actions get rejected.

**Comment by zbraniecki** [comment]
Ah, so maybe all I have to do is pass the followup action that verifies the outcome of the previous and reacts to it. Thanks!
